name: Steam Workshop

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workshop:
    uses: ./.github/workflows/publish-workshop.yml
    with:
      workshop-id: '3706460551'
      build-mode: ready
      project-directory: '.'
    secrets:
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
      STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
